const fs = require('fs');
const path = require('path');

const chainId = process.argv[2];

if (!chainId) {
    console.error("❌ Please provide a chainId! Example: node format_deployments.js 16661");
    process.exit(1);
}

const frontendPath = path.join(__dirname, '../frontend/src/deployments.json');

// Read temporary addresses
const tempPath = './temp_addresses.json';
if (!fs.existsSync(tempPath)) {
    console.error("❌ temp_addresses.json not found. Did you run `forge script` first?");
    process.exit(1);
}
const addresses = JSON.parse(fs.readFileSync(tempPath, 'utf8'));

// Read ABIs generated by Forge
const agentraArtifact = JSON.parse(fs.readFileSync('./out/Agentra.sol/Agentra.json', 'utf8'));
const registryArtifact = JSON.parse(fs.readFileSync('./out/AgentraRegistry.sol/AgentraRegistry.json', 'utf8'));

// Construct the master payload
let deployments = {};
if (fs.existsSync(frontendPath)) {
    const rawData = fs.readFileSync(frontendPath, 'utf8').trim();
    if (rawData) {
        try {
            deployments = JSON.parse(rawData);
        } catch (e) {
            console.warn("⚠️ deployments.json was malformed. Overwriting with fresh JSON.");
            deployments = {};
        }
    }
}

// 1. Insert placeholders for the ABIs
deployments[chainId] = {
    Agentra: {
        address: addresses.Agentra,
        abi: "%%AGENTRA_ABI%%"
    },
    AgentraRegistry: {
        address: addresses.AgentraRegistry,
        abi: "%%REGISTRY_ABI%%"
    }
};

// 2. Format the overall structure nicely
let outputJson = JSON.stringify(deployments, null, 2);

// 3. Swap the placeholders with the minified ABI arrays
outputJson = outputJson.replace('"%%AGENTRA_ABI%%"', JSON.stringify(agentraArtifact.abi));
outputJson = outputJson.replace('"%%REGISTRY_ABI%%"', JSON.stringify(registryArtifact.abi));

// Write the final clean JSON to the frontend
fs.writeFileSync(frontendPath, outputJson);
fs.unlinkSync('./temp_addresses.json'); 
console.log(`✅ Deployments auto-synced to frontend for Chain ID ${chainId}`);