# contracts/foundry.toml
[profile.default]
solc_version = "0.8.24"   # was 0.8.20 — OZ needs ^0.8.24, bump to match
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "../" }
]